package com.codehills.carfuel.model;

import java.util.ArrayList;
import java.util.List;

/**
 * Car model representing a vehicle in the system.
 * 
 * This class stores basic car information and maintains a list of fuel entries.
 * Each car has a unique ID that is auto-generated when created.
 */
public class Car {

    /**
     * Unique identifier for the car.
     * This is auto-generated by the service layer using an AtomicLong counter.
     */
    private Long id;

    /**
     * Car brand/manufacturer (e.g., "Toyota", "Honda", "Ford")
     */
    private String brand;

    /**
     * Car model name (e.g., "Corolla", "Civic", "F-150")
     */
    private String model;

    /**
     * Year the car was manufactured (e.g., 2018, 2020)
     */
    private Integer year;

    /**
     * List of fuel entries for this car.
     * Each entry records a refueling event with liters, price, and odometer
     * reading.
     */
    private List<FuelEntry> fuelEntries;

    /**
     * Default constructor.
     */
    public Car() {
        this.fuelEntries = new ArrayList<>();
    }

    /**
     * Constructor for creating a new car without an ID.
     * The ID will be assigned by the service layer.
     * 
     * @param brand Car brand
     * @param model Car model
     * @param year  Manufacturing year
     */
    public Car(String brand, String model, Integer year) {
        this.brand = brand;
        this.model = model;
        this.year = year;
        this.fuelEntries = new ArrayList<>();
    }

    /**
     * Full constructor with all fields.
     * 
     * @param id          Car ID
     * @param brand       Car brand
     * @param model       Car model
     * @param year        Manufacturing year
     * @param fuelEntries List of fuel entries
     */
    public Car(Long id, String brand, String model, Integer year, List<FuelEntry> fuelEntries) {
        this.id = id;
        this.brand = brand;
        this.model = model;
        this.year = year;
        this.fuelEntries = fuelEntries != null ? fuelEntries : new ArrayList<>();
    }

    // Getters and Setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getBrand() {
        return brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public String getModel() {
        return model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public Integer getYear() {
        return year;
    }

    public void setYear(Integer year) {
        this.year = year;
    }

    public List<FuelEntry> getFuelEntries() {
        return fuelEntries;
    }

    public void setFuelEntries(List<FuelEntry> fuelEntries) {
        this.fuelEntries = fuelEntries;
    }
}
