package com.codehills.carfuel.model;

import java.time.LocalDateTime;

/**
 * FuelEntry model representing a single refueling event.
 * 
 * Each fuel entry records:
 * - How much fuel was added (liters)
 * - How much it cost (price)
 * - The odometer reading at the time of refueling
 * - When the entry was created (timestamp)
 * 
 * This data is used to calculate fuel consumption statistics.
 */
public class FuelEntry {

    /**
     * Unique identifier for this fuel entry.
     * Auto-generated by the service layer.
     */
    private Long id;

    /**
     * Amount of fuel added in liters.
     * Must be a positive number.
     */
    private Double liters;

    /**
     * Total cost of the fuel in the local currency.
     * Must be a positive number.
     */
    private Double price;

    /**
     * Odometer reading at the time of refueling (in kilometers or miles).
     * This is used to calculate distance traveled between refuelings.
     */
    private Integer odometer;

    /**
     * Timestamp when this fuel entry was created.
     * Automatically set by the service layer when adding a new entry.
     */
    private LocalDateTime createdAt;

    /**
     * Default constructor.
     */
    public FuelEntry() {
    }

    /**
     * Constructor for creating a new fuel entry without ID and timestamp.
     * These will be set by the service layer.
     * 
     * @param liters   Amount of fuel in liters
     * @param price    Total cost
     * @param odometer Odometer reading
     */
    public FuelEntry(Double liters, Double price, Integer odometer) {
        this.liters = liters;
        this.price = price;
        this.odometer = odometer;
        this.createdAt = LocalDateTime.now();
    }

    /**
     * Full constructor with all fields.
     * 
     * @param id        Fuel entry ID
     * @param liters    Amount of fuel in liters
     * @param price     Total cost
     * @param odometer  Odometer reading
     * @param createdAt Timestamp
     */
    public FuelEntry(Long id, Double liters, Double price, Integer odometer, LocalDateTime createdAt) {
        this.id = id;
        this.liters = liters;
        this.price = price;
        this.odometer = odometer;
        this.createdAt = createdAt;
    }

    // Getters and Setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Double getLiters() {
        return liters;
    }

    public void setLiters(Double liters) {
        this.liters = liters;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public Integer getOdometer() {
        return odometer;
    }

    public void setOdometer(Integer odometer) {
        this.odometer = odometer;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}
